spring:
  application:
    name: coupon-consumer
server:
  port: 8081
management:
  metrics:
    tag:
      application:
        ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus